
DROP TABLE IF EXISTS `pays`;
CREATE TABLE IF NOT EXISTS `pays` (
  `num_code` int(3) NOT NULL DEFAULT '0',
  `alpha_2_code` varchar(2) DEFAULT NULL,
  `alpha_3_code` varchar(3) DEFAULT NULL,
  `en_short_name` varchar(52) DEFAULT NULL,
  `nationality` varchar(39) DEFAULT NULL,
  PRIMARY KEY (`num_code`),
  UNIQUE KEY `alpha_2_code` (`alpha_2_code`),
  UNIQUE KEY `alpha_3_code` (`alpha_3_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `pays` (`num_code`, `alpha_2_code`, `alpha_3_code`, `en_short_name`, `nationality`) VALUES
("686", "SN", "SEN", "Sénégal", "Sénégalais"),
("4", "AF", "AFG", "Afghanistan", "Afghan"),
("248", "AX", "ALA", "Îles Åland", "Ålandais"),
("8", "AL", "ALB", "Albanie", "Albanais"),
("12", "DZ", "DZA", "Algérie", "Algérien"),
("16", "AS", "ASM", "Samoa américaines", "Samoan américain"),
("20", "AD", "AND", "Andorre", "Andorran"),
("24", "AO", "AGO", "Angola", "Angolais"),
("660", "AI", "AIA", "Anguilla", "Anguillais"),
("10", "AQ", "ATA", "Antarctique", "Antarctique"),
("28", "AG", "ATG", "Antigua-et-Barbuda", "Antiguais, Barbudien"),
("32", "AR", "ARG", "Argentine", "Argentin"),
("51", "AM", "ARM", "Arménie", "Arménien"),
("533", "AW", "ABW", "Aruba", "Arubais"),
("36", "AU", "AUS", "Australie", "Australien"),
("40", "AT", "AUT", "Autriche", "Autrichien"),
("31", "AZ", "AZE", "Azerbaïdjan", "Azéri"),
("44", "BS", "BHS", "Bahamas", "Bahaméen"),
("48", "BH", "BHR", "Bahreïn", "Bahreïni"),
("50", "BD", "BGD", "Bangladesh", "Bangladais"),
("52", "BB", "BRB", "Barbade", "Barbadien"),
("112", "BY", "BLR", "Bélarus", "Biélorusse"),
("56", "BE", "BEL", "Belgique", "Belge"),
("84", "BZ", "BLZ", "Belize", "Bélizien"),
("204", "BJ", "BEN", "Bénin", "Béninois"),
("60", "BM", "BMU", "Bermudes", "Bermudien"),
("64", "BT", "BTN", "Bhoutan", "Bhoutanais"),
("68", "BO", "BOL", "Bolivie (État plurinational de)", "Bolivien"),
("535", "BQ", "BES", "Bonaire, Saint-Eustache et Saba", "Bonaire"),
("70", "BA", "BIH", "Bosnie-Herzégovine", "Bosnien, Herzégovinien"),
("72", "BW", "BWA", "Botswana", "Botswanais"),
("74", "BV", "BVT", "Île Bouvet", "Bouvet Island"),
("76", "BR", "BRA", "Brésil", "Brésilien"),
("96", "BN", "BRN", "Brunéi Darussalam", "Brunéien"),
("100", "BG", "BGR", "Bulgarie", "Bulgare"),
("854", "BF", "BFA", "Burkina Faso", "Burkinabé"),
("108", "BI", "BDI", "Burundi", "Burundais"),
("132", "CV", "CPV", "Cap-Vert", "Cap-verdien"),
("116", "KH", "KHM", "Cambodge", "Cambodgien"),
("120", "CM", "CMR", "Cameroun", "Camerounais"),
("124", "CA", "CAN", "Canada", "Canadien"),
("136", "KY", "CYM", "Îles Caïmans", "Caïmanais"),
("140", "CF", "CAF", "République centrafricaine", "Centrafricain"),
("148", "TD", "TCD", "Tchad", "Tchadien"),
("152", "CL", "CHL", "Chili", "Chilien"),
("156", "CN", "CHN", "Chine", "Chinois"),
("162", "CX", "CXR", "Île Christmas", "Christmas Island"),
("166", "CC", "CCK", "Îles Cocos - Keeling", "Cocos Island"),
("170", "CO", "COL", "Colombie", "Colombien"),
("174", "KM", "COM", "Comores", "Comorien"),
("178", "CG", "COG", "Congo", "Congolais"),
("180", "CD", "COD", "Congo (République démocratique du)", "Congolais"),
("184", "CK", "COK", "Îles Cook", "Cook Island"),
("188", "CR", "CRI", "Costa Rica", "Costaricain"),
("384", "CI", "CIV", "Côte d'Ivoire", "Ivoirien"),
("191", "HR", "HRV", "Croatie", "Croate"),
("192", "CU", "CUB", "Cuba", "Cubain"),
("531", "CW", "CUW", "Curaçao", "Curaçao"),
("196", "CY", "CYP", "Chypre", "Chypriote"),
("203", "CZ", "CZE", "République tchèque", "Tchèque"),
("208", "DK", "DNK", "Danemark", "Danois"),
("262", "DJ", "DJI", "Djibouti", "Djiboutien"),
("212", "DM", "DMA", "Dominique", "Dominiquais"),
("214", "DO", "DOM", "République dominicaine", "Dominicain"),
("218", "EC", "ECU", "Équateur", "Équatorien"),
("818", "EG", "EGY", "Égypte", "Égyptien"),
("222", "SV", "SLV", "El Salvador", "Salvadorien"),
("226", "GQ", "GNQ", "Guinée équatoriale", "Équato-guinéen"),
("232", "ER", "ERI", "Érythrée", "Érythréen"),
("233", "EE", "EST", "Estonie", "Estonien"),
("231", "ET", "ETH", "Éthiopie", "Éthiopien"),
("238", "FK", "FLK", "Îles Malouines", "Falkland Island"),
("234", "FO", "FRO", "Îles Féroé", "Féroïen"),
("242", "FJ", "FJI", "Fidji", "Fidjien"),
("246", "FI", "FIN", "Finlande", "Finlandais"),
("250", "FR", "FRA", "France", "Français"),
("254", "GF", "GUF", "Guyane française", "Guyanais"),
("258", "PF", "PYF", "Polynésie française", "Polynésien"),
("260", "TF", "ATF", "Terres australes françaises", "French Southern Territories"),
("266", "GA", "GAB", "Gabon", "Gabonais"),
("270", "GM", "GMB", "Gambie", "Gambien"),
("268", "GE", "GEO", "Géorgie", "Géorgien"),
("276", "DE", "DEU", "Allemagne", "Allemand"),
("288", "GH", "GHA", "Ghana", "Ghanéen"),
("292", "GI", "GIB", "Gibraltar", "Gibraltar"),
("300", "GR", "GRC", "Grèce", "Grec"),
("304", "GL", "GRL", "Groenland", "Groenlandais"),
("308", "GD", "GRD", "Grenade", "Grenadien"),
("312", "GP", "GLP", "Guadeloupe", "Guadeloupéen"),
("316", "GU", "GUM", "Guam", "Guamien"),
("320", "GT", "GTM", "Guatemala", "Guatémaltèque"),
("831", "GG", "GGY", "Guernesey", "Channel Island"),
("324", "GN", "GIN", "Guinée", "Guinéen"),
("624", "GW", "GNB", "Guinée-Bissau", "Bissau-Guinéen"),
("328", "GY", "GUY", "Guyana", "Guyanien"),
("332", "HT", "HTI", "Haïti", "Haïtien"),
("334", "HM", "HMD", "Îles Heard-et-MacDonald", "Heard Island or McDonald Islands"),
("336", "VA", "VAT", "Saint-Siège", "Vatican"),
("340", "HN", "HND", "Honduras", "Hondurien"),
("344", "HK", "HKG", "Hong Kong", "Hongkongais"),
("348", "HU", "HUN", "Hongrie", "Hongrois"),
("352", "IS", "ISL", "Islande", "Islandais"),
("356", "IN", "IND", "Inde", "Indien"),
("360", "ID", "IDN", "Indonésie", "Indonésien"),
("364", "IR", "IRN", "Iran (République islamique d')", "Iranien"),
("368", "IQ", "IRQ", "Iraq", "Irakien"),
("372", "IE", "IRL", "Irlande", "Irlandais"),
("833", "IM", "IMN", "Île de Man", "Manx"),
("376", "IL", "ISR", "Israël", "Israélien"),
("380", "IT", "ITA", "Italie", "Italien"),
("388", "JM", "JAM", "Jamaïque", "Jamaïcain"),
("392", "JP", "JPN", "Japon", "Japonais"),
("832", "JE", "JEY", "Jersey", "Channel Island"),
("400", "JO", "JOR", "Jordanie", "Jordanien"),
("398", "KZ", "KAZ", "Kazakhstan", "Kazakh"),
("404", "KE", "KEN", "Kenya", "Kényan"),
("296", "KI", "KIR", "Kiribati", "I-Kiribati"),
("408", "KP", "PRK", "Corée (République populaire démocratique de)", "North Korean"),
("410", "KR", "KOR", "Corée (République de)", "South Korean"),
("414", "KW", "KWT", "Koweït", "Koweïtien"),
("417", "KG", "KGZ", "Kirghizistan", "Kirghize"),
("418", "LA", "LAO", "République démocratique populaire lao", "Laotian"),
("428", "LV", "LVA", "Lettonie", "Letton"),
("422", "LB", "LBN", "Liban", "Libanais"),
("426", "LS", "LSO", "Lesotho", "Basotho"),
("430", "LR", "LBR", "Liberia", "Libérien"),
("434", "LY", "LBY", "Libye", "Libyen"),
("438", "LI", "LIE", "Liechtenstein", "Liechtensteinois"),
("440", "LT", "LTU", "Lituanie", "Lituanien"),
("442", "LU", "LUX", "Luxembourg", "Luxembourgeois"),
("446", "MO", "MAC", "Macao", "Macanais"),
("807", "MK", "MKD", "Macédoine du Nord", "Macedonian"),
("450", "MG", "MDG", "Madagascar", "Malagasy"),
("454", "MW", "MWI", "Malawi", "Malawien"),
("458", "MY", "MYS", "Malaisie", "Malaisien"),
("462", "MV", "MDV", "Maldives", "Maldivien"),
("466", "ML", "MLI", "Mali", "Malien"),
("470", "MT", "MLT", "Malte", "Maltais"),
("584", "MH", "MHL", "Îles Marshall", "Marshallese"),
("474", "MQ", "MTQ", "Martinique", "Martiniquais"),
("478", "MR", "MRT", "Mauritanie", "Mauritanien"),
("480", "MU", "MUS", "Maurice", "Mauricien"),
("175", "YT", "MYT", "Mayotte", "Mahorais"),
("484", "MX", "MEX", "Mexique", "Mexicain"),
("583", "FM", "FSM", "Micronésie (États fédérés de)", "Micronesian"),
("498", "MD", "MDA", "Moldova (République de)", "Moldave"),
("492", "MC", "MCO", "Monaco", "Monégasque"),
("496", "MN", "MNG", "Mongolie", "Mongol"),
("499", "ME", "MNE", "Monténégro", "Monténégrin"),
("500", "MS", "MSR", "Montserrat", "Montserratien"),
("504", "MA", "MAR", "Maroc", "Marocain"),
("508", "MZ", "MOZ", "Mozambique", "Mozambicain"),
("104", "MM", "MMR", "Myanmar", "Birman"),
("516", "NA", "NAM", "Namibie", "Namibien"),
("520", "NR", "NRU", "Nauru", "Nauruan"),
("524", "NP", "NPL", "Népal", "Népalais"),
("528", "NL", "NLD", "Pays-Bas", "Néerlandais"),
("540", "NC", "NCL", "Nouvelle-Calédonie", "Néo-Calédonien"),
("554", "NZ", "NZL", "Nouvelle-Zélande", "Néo-Zélandais"),
("558", "NI", "NIC", "Nicaragua", "Nicaraguayen"),
("562", "NE", "NER", "Niger", "Nigérien"),
("566", "NG", "NGA", "Nigeria", "Nigérian"),
("570", "NU", "NIU", "Niue", "Niuéen"),
("574", "NF", "NFK", "Île Norfolk", "Norfolk Island"),
("580", "MP", "MNP", "Îles Mariannes du Nord", "Northern Marianan"),
("578", "NO", "NOR", "Norvège", "Norvégien"),
("512", "OM", "OMN", "Oman", "Omanais"),
("586", "PK", "PAK", "Pakistan", "Pakistanais"),
("585", "PW", "PLW", "Palaos", "Palauan"),
("275", "PS", "PSE", "Palestine, État de", "Palestinian"),
("591", "PA", "PAN", "Panama", "Panaméen"),
("598", "PG", "PNG", "Papouasie-Nouvelle-Guinée", "Papouasien"),
("600", "PY", "PRY", "Paraguay", "Paraguayen"),
("604", "PE", "PER", "Pérou", "Péruvien"),
("608", "PH", "PHL", "Philippines", "Philippin"),
("612", "PN", "PCN", "Pitcairn", "Pitcairn Island"),
("616", "PL", "POL", "Pologne", "Polonais"),
("620", "PT", "PRT", "Portugal", "Portugais"),
("630", "PR", "PRI", "Porto Rico", "Porto-ricain"),
("634", "QA", "QAT", "Qatar", "Qatari"),
("638", "RE", "REU", "Réunion", "Réunionnais"),
("642", "RO", "ROU", "Roumanie", "Roumain"),
("643", "RU", "RUS", "Fédération de Russie", "Russe"),
("646", "RW", "RWA", "Rwanda", "Rwandais"),
("652", "BL", "BLM", "Saint-Barthélemy", "Barthélemois"),
("654", "SH", "SHN", "Sainte-Hélène, Ascension et Tristan da Cunha", "Saint Helenian"),
("659", "KN", "KNA", "Saint-Kitts-et-Nevis", "Kittitien, Névisien"),
("662", "LC", "LCA", "Sainte-Lucie", "Saint Lucian"),
("663", "MF", "MAF", "Saint-Martin (partie française)", "Saint-Martinois"),
("666", "PM", "SPM", "Saint-Pierre-et-Miquelon", "Saint-Pierrais, Miquelonnais"),
("670", "VC", "VCT", "Saint-Vincent-et-les Grenadines", "Saint-Vincentais, Grenadin"),
("882", "WS", "WSM", "Samoa", "Samoan"),
("674", "SM", "SMR", "Saint-Marin", "Saint-Marinais"),
("678", "ST", "STP", "Sao Tomé-et-Principe", "Santoméen, Principe"),
("682", "SA", "SAU", "Arabie saoudite", "Saoudien"),
("688", "RS", "SRB", "Serbie", "Serbe"),
("690", "SC", "SYC", "Seychelles", "Seychellois"),
("694", "SL", "SLE", "Sierra Leone", "Sierra-léonais"),
("702", "SG", "SGP", "Singapour", "Singapourien"),
("534", "SX", "SXM", "Saint-Martin (partie néerlandaise)", "Sint Maartener"),
("703", "SK", "SVK", "Slovaquie", "Slovaque"),
("705", "SI", "SVN", "Slovénie", "Slovène"),
("90", "SB", "SLB", "Îles Salomon", "Salomonais"),
("706", "SO", "SOM", "Somalie", "Somalien"),
("710", "ZA", "ZAF", "Afrique du Sud", "Sud-Africain"),
("239", "GS", "SGS", "Géorgie du Sud-et-les Îles Sandwich du Sud", "South Georgia"),
("728", "SS", "SSD", "Soudan du Sud", "South Sudanese"),
("724", "ES", "ESP", "Espagne", "Espagnol"),
("144", "LK", "LKA", "Sri Lanka", "Sri Lankais"),
("729", "SD", "SDN", "Soudan", "Soudanais"),
("740", "SR", "SUR", "Suriname", "Surinamais"),
("744", "SJ", "SJM", "Svalbard et Jan Mayen", "Svalbard"),
("752", "SE", "SWE", "Suède", "Suédois"),
("756", "CH", "CHE", "Suisse", "Suisse"),
("760", "SY", "SYR", "République arabe syrienne", "Syrien"),
("158", "TW", "TWN", "Taiwan", "Taïwanais"),
("762", "TJ", "TJK", "Tadjikistan", "Tadjik"),
("834", "TZ", "TZA", "Tanzanie, République-Unie de", "Tanzanien"),
("764", "TH", "THA", "Thaïlande", "Thaïlandais"),
("626", "TL", "TLS", "Timor-Leste", "Timorais"),
("768", "TG", "TGO", "Togo", "Togolais"),
("772", "TK", "TKL", "Tokelau", "Tokelauan"),
("776", "TO", "TON", "Tonga", "Tongan"),
("780", "TT", "TTO", "Trinité-et-Tobago", "Trinidadien"),
("788", "TN", "TUN", "Tunisie", "Tunisien"),
("792", "TR", "TUR", "Turquie", "Turc"),
("795", "TM", "TKM", "Turkménistan", "Turkmène"),
("796", "TC", "TCA", "Îles Turques-et-Caïques", "Turks and Caicos Island"),
("798", "TV", "TUV", "Tuvalu", "Tuvaluan"),
("800", "UG", "UGA", "Ouganda", "Ougandais"),
("804", "UA", "UKR", "Ukraine", "Ukrainien"),
("784", "AE", "ARE", "Émirats arabes unis", "Émirien"),
("826", "GB", "GBR", "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", "Britannique"),
("840", "US", "USA", "États-Unis d'Amérique", "Américain"),
("858", "UY", "URY", "Uruguay", "Uruguayen"),
("860", "UZ", "UZB", "Ouzbékistan", "Ouzbek"),
("548", "VU", "VUT", "Vanuatu", "Vanuatais"),
("862", "VE", "VEN", "Venezuela (République bolivarienne du)", "Vénézuélien"),
("704", "VN", "VNM", "Viet Nam", "Vietnamien"),
("92", "VG", "VGB", "Îles Vierges britanniques", "Virgin Island"),
("850", "VI", "VIR", "Îles Vierges des États-Unis", "Virgin Island"),
("876", "WF", "WLF", "Wallis-et-Futuna", "Wallis and Futuna Island"),
("732", "EH", "ESH", "Sahara occidental", "Sahraoui"),
("887", "YE", "YEM", "Yémen", "Yéménite"),
("894", "ZM", "ZMB", "Zambie", "Zambien"),
("716", "ZW", "ZWE", "Zimbabwe", "Zimbabwéen");

